[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.87"
image = "0.24.6"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true
